spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    hiddenmethod:
      filter:
        enabled: true
    throw-exception-if-no-handler-found: true
  profiles:
    include: datasource, googleinfo

server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  mapper-locations: /mapper/**/*.xml
  type-aliases-package: com.spring.itjunior.domain, com.spring.itjunior.dto
